#!/usr/bin/env python3
"""
SKVA Core Engine v2 — async parallel agent spawn, Python-side heartbeat,
real error detection (not LLM self-report).
"""
import json, os, sys, time, subprocess, threading
from pathlib import Path

HERMES_HOME = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))

def log(msg, level="INFO"):
    ts = time.strftime("%H:%M:%S")
    print(f"[{ts}] [{level}] {msg}", flush=True)

class AgentProcess:
    """
    Represents a running Hermes agent. Heartbeat is generated by Python,
    NOT by the LLM (LLMs can't multitask).
    """
    def __init__(self, role, prompt, project_dir, timeout=900):
        self.role = role
        self.project_dir = Path(project_dir)
        self.timeout = timeout
        self.proc = None
        self.stdout = ""
        self.stderr = ""
        self.start_time = None
        self.done = False
        self.success = False
        self.error = ""

        # Створюємо директорії
        artifacts_dir = self.project_dir / ".hermes" / "artifacts" / role
        signals_dir = self.project_dir / ".hermes" / "signals" / "heartbeat"
        artifacts_dir.mkdir(parents=True, exist_ok=True)
        signals_dir.mkdir(parents=True, exist_ok=True)

        # Prompt для агента — без heartbeat інструкцій (це робить Python)
        self.prompt = f"""Твоя роль: {role}.
Проект: {project_dir}
Задача: {prompt}

Працюй в {artifacts_dir}/
Коли готово — створи файл {self.project_dir / '.hermes' / 'signals' / f'.{role}.done'}
Якщо помилка — напиши причину в {self.project_dir / '.hermes' / 'signals' / f'.{role}.fail'}
Не чіпай файли інших агентів."""

    def _heartbeat_loop(self):
        """Python-side heartbeat: writes .live file every 30s."""
        hb_file = self.project_dir / ".hermes" / "signals" / "heartbeat" / f"{self.role}.live"
        try:
            while not self.done:
                hb_file.parent.mkdir(parents=True, exist_ok=True)
                hb_file.write_text(json.dumps({"ts": time.time(), "role": self.role, "pid": self.proc.pid if self.proc else 0}))
                time.sleep(30)
        except:
            pass

    def _timeout_killer(self):
        """Kill process if it runs too long."""
        time.sleep(self.timeout)
        if not self.done and self.proc and self.proc.poll() is None:
            log(f"{self.role} TIMEOUT ({self.timeout}s), killing...", "WARN")
            self.proc.kill()
            self.error = f"timeout after {self.timeout}s"
            self.success = False
            self.done = True

    def start(self):
        """Start the agent process in background."""
        log(f"Starting {self.role} (timeout={self.timeout}s)")
        self.start_time = time.time()

        self.proc = subprocess.Popen(
            ["hermes", "chat", "-q", self.prompt],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            env={**os.environ, "HERMES_HOME": HERMES_HOME}
        )

        # Heartbeat in separate thread (Python, not LLM)
        hb_thread = threading.Thread(target=self._heartbeat_loop, daemon=True)
        hb_thread.start()

        # Timeout killer
        tk_thread = threading.Thread(target=self._timeout_killer, daemon=True)
        tk_thread.start()

        return self

    def wait(self):
        """Wait for process to finish. Returns self."""
        try:
            self.stdout, self.stderr = self.proc.communicate(timeout=self.timeout + 30)
            self.done = True
            rc = self.proc.returncode

            # Check for common LLM failure patterns
            errors_found = []
            output = (self.stdout + " " + self.stderr).lower()
            failure_patterns = [
                ("i cannot", "LLM refused"),
                ("i can't", "LLM refused"),
                ("apologize", "LLM apologized"),
                ("unable to", "LLM unable"),
                ("not possible", "LLM impossible"),
                ("error", "error in output"),
                ("traceback", "python error"),
            ]
            for pattern, reason in failure_patterns:
                if pattern in output:
                    errors_found.append(reason)

            if errors_found:
                self.error = "; ".join(errors_found)
                self.success = False
                log(f"{self.role} detected failure: {self.error}", "WARN")
            elif rc != 0:
                self.error = f"exit code {rc}"
                self.success = False
            else:
                # Check if .done was created
                done_file = self.project_dir / ".hermes" / "signals" / f".{self.role}.done"
                if done_file.exists():
                    self.success = True
                else:
                    # Maybe it created files despite not signaling done
                    artifacts = list((self.project_dir / ".hermes" / "artifacts" / self.role).rglob("*"))
                    if artifacts:
                        log(f"{self.role} created {len(artifacts)} files but no .done signal", "WARN")
                        self.success = True  # be optimistic
                    else:
                        self.error = "no artifacts and no .done signal"
                        self.success = False

        except subprocess.TimeoutExpired:
            self.proc.kill()
            self.error = f"timeout after {self.timeout}s"
            self.success = False
            self.done = True

        elapsed = time.time() - self.start_time
        icon = "✅" if self.success else "❌"
        log(f"{icon} {self.role} ({elapsed:.0f}s)" + (f": {self.error}" if self.error else ""))
        return self

    def is_alive(self):
        """Check if process is still running."""
        return self.proc and self.proc.poll() is None

def spawn_parallel(agents_config, project_dir):
    """
    Spawn multiple agents in PARALLEL (not sequential).
    agents_config: list of {role, prompt, timeout}
    Returns: list of AgentProcess results.
    """
    agents = []
    for cfg in agents_config:
        agent = AgentProcess(
            role=cfg["role"],
            prompt=cfg["prompt"],
            project_dir=project_dir,
            timeout=cfg.get("timeout", 900)
        ).start()
        agents.append(agent)

    # Wait for ALL to complete in parallel
    for agent in agents:
        agent.wait()

    return agents

def check_gate_smart(agents, phase, project_dir, timeout=600):
    """
    Smart gate check: waits for ALL agents in this phase to complete
    OR timeout. Returns True if any agent produced useful output.
    """
    done_file = Path(project_dir) / ".hermes" / "signals" / f".{phase}.done"
    fail_file = Path(project_dir) / ".hermes" / "signals" / f".{phase}.fail"

    all_success = all(a.success for a in agents)
    any_success = any(a.success for a in agents)

    if all_success:
        log(f"Gate {phase}: ALL agents passed ✅", "OK")
        done_file.touch()
        return True
    elif any_success:
        log(f"Gate {phase}: {sum(1 for a in agents if a.success)}/{len(agents)} passed ⚠️", "WARN")
        done_file.touch()  # partial pass — let next phase try
        return True
    else:
        reasons = [a.error for a in agents if a.error]
        log(f"Gate {phase}: ALL failed — {reasons}", "ERROR")
        fail_file.write_text(json.dumps({"reasons": reasons}))
        return False

def verify_artifacts(project_dir, phase):
    """Verify phase output quality."""
    project = Path(project_dir)
    arts = project / ".hermes" / "artifacts"

    if phase == "solo":
        files = list((arts / "fullstack").rglob("*"))
        if files:
            log(f"✅ {len(files)} artifacts created", "OK")
            for f in files[:3]:
                size = f.stat().st_size
                log(f"  {f.relative_to(arts)} ({size}b)", "OK")
            return True
        log("❌ No artifacts", "ERROR")
        return False

    if phase == "council":
        spec = arts / "council" / "spec.md"
        arch = arts / "council" / "arch.md"
        if not spec.exists():
            log("❌ spec.md missing", "ERROR")
            return False
        if spec.stat().st_size < 50:
            log(f"❌ spec.md too small ({spec.stat().st_size}b)", "ERROR")
            return False
        log(f"✅ spec.md ({spec.stat().st_size}b)", "OK")
        if arch.exists():
            log(f"✅ arch.md ({arch.stat().st_size}b)", "OK")
        return True

    return True

def solo(request, project_dir="."):
    """Solo method: one agent, parallel monitoring."""
    project_dir = os.path.abspath(project_dir)
    log(f"=== SOLO: {request} ===")
    start = time.time()

    agents = spawn_parallel([
        {"role": "fullstack", "prompt": request, "timeout": 900}
    ], project_dir)

    ok = check_gate_smart(agents, "solo", project_dir)
    verified = verify_artifacts(project_dir, "solo")

    elapsed = time.time() - start
    log(f"=== SOLO DONE ({elapsed:.0f}s) ===")
    return ok and verified

def council(request, project_dir):
    """Council phase: Architect + Analyst in PARALLEL."""
    log("=== COUNCIL ===")
    agents = spawn_parallel([
        {"role": "architect", "prompt": f"Write architecture spec for: {request}", "timeout": 600},
        {"role": "analyst", "prompt": f"Write requirements for: {request}", "timeout": 600},
    ], project_dir)
    return check_gate_smart(agents, "council", project_dir)

def factory(request, project_dir):
    """Factory phase: Developer writes code."""
    log("=== FACTORY ===")
    agents = spawn_parallel([
        {"role": "developer", "prompt": f"Implement per spec in artifacts/council: {request}", "timeout": 1800},
    ], project_dir)
    return check_gate_smart(agents, "factory", project_dir)
